/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminNavRouteImport } from './routes/_adminNav'
import { Route as CustomerNavRouteImport } from './routes/_customerNav'
import { Route as MerchantNavRouteImport } from './routes/_merchantNav'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as RegisterMerchantRouteImport } from './routes/register-merchant'
import { Route as AdminNavAdminRouteImport } from './routes/_adminNav.admin'
import { Route as CustomerNavIndexRouteImport } from './routes/_customerNav.index'
import { Route as CustomerNavExploreRouteImport } from './routes/_customerNav.explore'
import { Route as CustomerNavOrdersRouteImport } from './routes/_customerNav.orders'
import { Route as CustomerNavProfileRouteImport } from './routes/_customerNav.profile'
import { Route as MerchantNavMerchantRouteImport } from './routes/_merchantNav.merchant'
import { Route as PublicLoginRouteImport } from './routes/_public.login'
import { Route as PublicOnboardingRouteImport } from './routes/_public.onboarding'
import { Route as PublicRegisterRouteImport } from './routes/_public.register'
import { Route as MerchantEditProfileRouteImport } from './routes/merchant.edit-profile'
import { Route as MerchantsIdRouteImport } from './routes/merchants.$id'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as PaymentOrderIdRouteImport } from './routes/payment.$orderId'
import { Route as PaymentErrorRouteImport } from './routes/payment.error'
import { Route as PaymentFinishRouteImport } from './routes/payment.finish'
import { Route as PaymentUnfinishRouteImport } from './routes/payment.unfinish'
import { Route as ReviewOrderIdRouteImport } from './routes/review.$orderId'
import { Route as AdminNavAdminIndexRouteImport } from './routes/_adminNav.admin.index'
import { Route as AdminNavAdminProfileRouteImport } from './routes/_adminNav.admin.profile'
import { Route as AdminNavAdminReportsRouteImport } from './routes/_adminNav.admin.reports'
import { Route as AdminNavAdminReviewsRouteImport } from './routes/_adminNav.admin.reviews'
import { Route as MerchantNavMerchantIndexRouteImport } from './routes/_merchantNav.merchant.index'
import { Route as MerchantNavMerchantOrdersRouteImport } from './routes/_merchantNav.merchant.orders'
import { Route as MerchantNavMerchantProfileRouteImport } from './routes/_merchantNav.merchant.profile'
import { Route as MerchantNavMerchantServicesRouteImport } from './routes/_merchantNav.merchant.services'
import { Route as AdminApplicationsIdRouteImport } from './routes/admin.applications.$id'
import { Route as AdminReportsIdRouteImport } from './routes/admin.reports.$id'
import { Route as MerchantOrdersIdRouteImport } from './routes/merchant.orders.$id'

const AdminNavRoute = AdminNavRouteImport.update({
  id: '/_adminNav',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerNavRoute = CustomerNavRouteImport.update({
  id: '/_customerNav',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantNavRoute = MerchantNavRouteImport.update({
  id: '/_merchantNav',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterMerchantRoute = RegisterMerchantRouteImport.update({
  id: '/register-merchant',
  path: '/register-merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNavAdminRoute = AdminNavAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminNavRoute,
} as any)
const CustomerNavIndexRoute = CustomerNavIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerNavRoute,
} as any)
const CustomerNavExploreRoute = CustomerNavExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => CustomerNavRoute,
} as any)
const CustomerNavOrdersRoute = CustomerNavOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => CustomerNavRoute,
} as any)
const CustomerNavProfileRoute = CustomerNavProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerNavRoute,
} as any)
const MerchantNavMerchantRoute = MerchantNavMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => MerchantNavRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOnboardingRoute = PublicOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const MerchantEditProfileRoute = MerchantEditProfileRouteImport.update({
  id: '/merchant/edit-profile',
  path: '/merchant/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsIdRoute = MerchantsIdRouteImport.update({
  id: '/merchants/$id',
  path: '/merchants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentOrderIdRoute = PaymentOrderIdRouteImport.update({
  id: '/payment/$orderId',
  path: '/payment/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentErrorRoute = PaymentErrorRouteImport.update({
  id: '/payment/error',
  path: '/payment/error',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFinishRoute = PaymentFinishRouteImport.update({
  id: '/payment/finish',
  path: '/payment/finish',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentUnfinishRoute = PaymentUnfinishRouteImport.update({
  id: '/payment/unfinish',
  path: '/payment/unfinish',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewOrderIdRoute = ReviewOrderIdRouteImport.update({
  id: '/review/$orderId',
  path: '/review/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNavAdminIndexRoute = AdminNavAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminNavAdminRoute,
} as any)
const AdminNavAdminProfileRoute = AdminNavAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminNavAdminRoute,
} as any)
const AdminNavAdminReportsRoute = AdminNavAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminNavAdminRoute,
} as any)
const AdminNavAdminReviewsRoute = AdminNavAdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminNavAdminRoute,
} as any)
const MerchantNavMerchantIndexRoute =
  MerchantNavMerchantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MerchantNavMerchantRoute,
  } as any)
const MerchantNavMerchantOrdersRoute =
  MerchantNavMerchantOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => MerchantNavMerchantRoute,
  } as any)
const MerchantNavMerchantProfileRoute =
  MerchantNavMerchantProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => MerchantNavMerchantRoute,
  } as any)
const MerchantNavMerchantServicesRoute =
  MerchantNavMerchantServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => MerchantNavMerchantRoute,
  } as any)
const AdminApplicationsIdRoute = AdminApplicationsIdRouteImport.update({
  id: '/admin/applications/$id',
  path: '/admin/applications/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsIdRoute = AdminReportsIdRouteImport.update({
  id: '/admin/reports/$id',
  path: '/admin/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantOrdersIdRoute = MerchantOrdersIdRouteImport.update({
  id: '/merchant/orders/$id',
  path: '/merchant/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof CustomerNavIndexRoute
  '/checkout': typeof CheckoutRoute
  '/edit-profile': typeof EditProfileRoute
  '/register-merchant': typeof RegisterMerchantRoute
  '/admin': typeof AdminNavAdminRouteWithChildren
  '/explore': typeof CustomerNavExploreRoute
  '/orders': typeof CustomerNavOrdersRoute
  '/profile': typeof CustomerNavProfileRoute
  '/merchant': typeof MerchantNavMerchantRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/onboarding': typeof PublicOnboardingRoute
  '/register': typeof PublicRegisterRoute
  '/merchant/edit-profile': typeof MerchantEditProfileRoute
  '/merchants/$id': typeof MerchantsIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/payment/$orderId': typeof PaymentOrderIdRoute
  '/payment/error': typeof PaymentErrorRoute
  '/payment/finish': typeof PaymentFinishRoute
  '/payment/unfinish': typeof PaymentUnfinishRoute
  '/review/$orderId': typeof ReviewOrderIdRoute
  '/admin/profile': typeof AdminNavAdminProfileRoute
  '/admin/reports': typeof AdminNavAdminReportsRoute
  '/admin/reviews': typeof AdminNavAdminReviewsRoute
  '/merchant/orders': typeof MerchantNavMerchantOrdersRoute
  '/merchant/profile': typeof MerchantNavMerchantProfileRoute
  '/merchant/services': typeof MerchantNavMerchantServicesRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/merchant/orders/$id': typeof MerchantOrdersIdRoute
  '/admin/': typeof AdminNavAdminIndexRoute
  '/merchant/': typeof MerchantNavMerchantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof CustomerNavIndexRoute
  '/checkout': typeof CheckoutRoute
  '/edit-profile': typeof EditProfileRoute
  '/register-merchant': typeof RegisterMerchantRoute
  '/explore': typeof CustomerNavExploreRoute
  '/orders': typeof CustomerNavOrdersRoute
  '/profile': typeof CustomerNavProfileRoute
  '/login': typeof PublicLoginRoute
  '/onboarding': typeof PublicOnboardingRoute
  '/register': typeof PublicRegisterRoute
  '/merchant/edit-profile': typeof MerchantEditProfileRoute
  '/merchants/$id': typeof MerchantsIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/payment/$orderId': typeof PaymentOrderIdRoute
  '/payment/error': typeof PaymentErrorRoute
  '/payment/finish': typeof PaymentFinishRoute
  '/payment/unfinish': typeof PaymentUnfinishRoute
  '/review/$orderId': typeof ReviewOrderIdRoute
  '/admin/profile': typeof AdminNavAdminProfileRoute
  '/admin/reports': typeof AdminNavAdminReportsRoute
  '/admin/reviews': typeof AdminNavAdminReviewsRoute
  '/merchant/orders': typeof MerchantNavMerchantOrdersRoute
  '/merchant/profile': typeof MerchantNavMerchantProfileRoute
  '/merchant/services': typeof MerchantNavMerchantServicesRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/merchant/orders/$id': typeof MerchantOrdersIdRoute
  '/admin': typeof AdminNavAdminIndexRoute
  '/merchant': typeof MerchantNavMerchantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_adminNav': typeof AdminNavRouteWithChildren
  '/_customerNav': typeof CustomerNavRouteWithChildren
  '/_merchantNav': typeof MerchantNavRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/edit-profile': typeof EditProfileRoute
  '/register-merchant': typeof RegisterMerchantRoute
  '/_adminNav/admin': typeof AdminNavAdminRouteWithChildren
  '/_customerNav/explore': typeof CustomerNavExploreRoute
  '/_customerNav/orders': typeof CustomerNavOrdersRoute
  '/_customerNav/profile': typeof CustomerNavProfileRoute
  '/_merchantNav/merchant': typeof MerchantNavMerchantRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/onboarding': typeof PublicOnboardingRoute
  '/_public/register': typeof PublicRegisterRoute
  '/merchant/edit-profile': typeof MerchantEditProfileRoute
  '/merchants/$id': typeof MerchantsIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/payment/$orderId': typeof PaymentOrderIdRoute
  '/payment/error': typeof PaymentErrorRoute
  '/payment/finish': typeof PaymentFinishRoute
  '/payment/unfinish': typeof PaymentUnfinishRoute
  '/review/$orderId': typeof ReviewOrderIdRoute
  '/_customerNav/': typeof CustomerNavIndexRoute
  '/_adminNav/admin/profile': typeof AdminNavAdminProfileRoute
  '/_adminNav/admin/reports': typeof AdminNavAdminReportsRoute
  '/_adminNav/admin/reviews': typeof AdminNavAdminReviewsRoute
  '/_merchantNav/merchant/orders': typeof MerchantNavMerchantOrdersRoute
  '/_merchantNav/merchant/profile': typeof MerchantNavMerchantProfileRoute
  '/_merchantNav/merchant/services': typeof MerchantNavMerchantServicesRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/merchant/orders/$id': typeof MerchantOrdersIdRoute
  '/_adminNav/admin/': typeof AdminNavAdminIndexRoute
  '/_merchantNav/merchant/': typeof MerchantNavMerchantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/edit-profile'
    | '/register-merchant'
    | '/admin'
    | '/explore'
    | '/orders'
    | '/profile'
    | '/merchant'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/merchant/edit-profile'
    | '/merchants/$id'
    | '/orders/$id'
    | '/payment/$orderId'
    | '/payment/error'
    | '/payment/finish'
    | '/payment/unfinish'
    | '/review/$orderId'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/reviews'
    | '/merchant/orders'
    | '/merchant/profile'
    | '/merchant/services'
    | '/admin/applications/$id'
    | '/admin/reports/$id'
    | '/merchant/orders/$id'
    | '/admin/'
    | '/merchant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/edit-profile'
    | '/register-merchant'
    | '/explore'
    | '/orders'
    | '/profile'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/merchant/edit-profile'
    | '/merchants/$id'
    | '/orders/$id'
    | '/payment/$orderId'
    | '/payment/error'
    | '/payment/finish'
    | '/payment/unfinish'
    | '/review/$orderId'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/reviews'
    | '/merchant/orders'
    | '/merchant/profile'
    | '/merchant/services'
    | '/admin/applications/$id'
    | '/admin/reports/$id'
    | '/merchant/orders/$id'
    | '/admin'
    | '/merchant'
  id:
    | '__root__'
    | '/_adminNav'
    | '/_customerNav'
    | '/_merchantNav'
    | '/_public'
    | '/checkout'
    | '/edit-profile'
    | '/register-merchant'
    | '/_adminNav/admin'
    | '/_customerNav/explore'
    | '/_customerNav/orders'
    | '/_customerNav/profile'
    | '/_merchantNav/merchant'
    | '/_public/login'
    | '/_public/onboarding'
    | '/_public/register'
    | '/merchant/edit-profile'
    | '/merchants/$id'
    | '/orders/$id'
    | '/payment/$orderId'
    | '/payment/error'
    | '/payment/finish'
    | '/payment/unfinish'
    | '/review/$orderId'
    | '/_customerNav/'
    | '/_adminNav/admin/profile'
    | '/_adminNav/admin/reports'
    | '/_adminNav/admin/reviews'
    | '/_merchantNav/merchant/orders'
    | '/_merchantNav/merchant/profile'
    | '/_merchantNav/merchant/services'
    | '/admin/applications/$id'
    | '/admin/reports/$id'
    | '/merchant/orders/$id'
    | '/_adminNav/admin/'
    | '/_merchantNav/merchant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminNavRoute: typeof AdminNavRouteWithChildren
  CustomerNavRoute: typeof CustomerNavRouteWithChildren
  MerchantNavRoute: typeof MerchantNavRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  EditProfileRoute: typeof EditProfileRoute
  RegisterMerchantRoute: typeof RegisterMerchantRoute
  MerchantEditProfileRoute: typeof MerchantEditProfileRoute
  MerchantsIdRoute: typeof MerchantsIdRoute
  OrdersIdRoute: typeof OrdersIdRoute
  PaymentOrderIdRoute: typeof PaymentOrderIdRoute
  PaymentErrorRoute: typeof PaymentErrorRoute
  PaymentFinishRoute: typeof PaymentFinishRoute
  PaymentUnfinishRoute: typeof PaymentUnfinishRoute
  ReviewOrderIdRoute: typeof ReviewOrderIdRoute
  AdminApplicationsIdRoute: typeof AdminApplicationsIdRoute
  AdminReportsIdRoute: typeof AdminReportsIdRoute
  MerchantOrdersIdRoute: typeof MerchantOrdersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_adminNav': {
      id: '/_adminNav'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminNavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_customerNav': {
      id: '/_customerNav'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CustomerNavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_merchantNav': {
      id: '/_merchantNav'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MerchantNavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-merchant': {
      id: '/register-merchant'
      path: '/register-merchant'
      fullPath: '/register-merchant'
      preLoaderRoute: typeof RegisterMerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminNav/admin': {
      id: '/_adminNav/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminNavAdminRouteImport
      parentRoute: typeof AdminNavRoute
    }
    '/_customerNav/': {
      id: '/_customerNav/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CustomerNavIndexRouteImport
      parentRoute: typeof CustomerNavRoute
    }
    '/_customerNav/explore': {
      id: '/_customerNav/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof CustomerNavExploreRouteImport
      parentRoute: typeof CustomerNavRoute
    }
    '/_customerNav/orders': {
      id: '/_customerNav/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof CustomerNavOrdersRouteImport
      parentRoute: typeof CustomerNavRoute
    }
    '/_customerNav/profile': {
      id: '/_customerNav/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof CustomerNavProfileRouteImport
      parentRoute: typeof CustomerNavRoute
    }
    '/_merchantNav/merchant': {
      id: '/_merchantNav/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantNavMerchantRouteImport
      parentRoute: typeof MerchantNavRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/onboarding': {
      id: '/_public/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof PublicOnboardingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/merchant/edit-profile': {
      id: '/merchant/edit-profile'
      path: '/merchant/edit-profile'
      fullPath: '/merchant/edit-profile'
      preLoaderRoute: typeof MerchantEditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants/$id': {
      id: '/merchants/$id'
      path: '/merchants/$id'
      fullPath: '/merchants/$id'
      preLoaderRoute: typeof MerchantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$orderId': {
      id: '/payment/$orderId'
      path: '/payment/$orderId'
      fullPath: '/payment/$orderId'
      preLoaderRoute: typeof PaymentOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/error': {
      id: '/payment/error'
      path: '/payment/error'
      fullPath: '/payment/error'
      preLoaderRoute: typeof PaymentErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/finish': {
      id: '/payment/finish'
      path: '/payment/finish'
      fullPath: '/payment/finish'
      preLoaderRoute: typeof PaymentFinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/unfinish': {
      id: '/payment/unfinish'
      path: '/payment/unfinish'
      fullPath: '/payment/unfinish'
      preLoaderRoute: typeof PaymentUnfinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$orderId': {
      id: '/review/$orderId'
      path: '/review/$orderId'
      fullPath: '/review/$orderId'
      preLoaderRoute: typeof ReviewOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminNav/admin/': {
      id: '/_adminNav/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminNavAdminIndexRouteImport
      parentRoute: typeof AdminNavAdminRoute
    }
    '/_adminNav/admin/profile': {
      id: '/_adminNav/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminNavAdminProfileRouteImport
      parentRoute: typeof AdminNavAdminRoute
    }
    '/_adminNav/admin/reports': {
      id: '/_adminNav/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminNavAdminReportsRouteImport
      parentRoute: typeof AdminNavAdminRoute
    }
    '/_adminNav/admin/reviews': {
      id: '/_adminNav/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminNavAdminReviewsRouteImport
      parentRoute: typeof AdminNavAdminRoute
    }
    '/_merchantNav/merchant/': {
      id: '/_merchantNav/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantNavMerchantIndexRouteImport
      parentRoute: typeof MerchantNavMerchantRoute
    }
    '/_merchantNav/merchant/orders': {
      id: '/_merchantNav/merchant/orders'
      path: '/orders'
      fullPath: '/merchant/orders'
      preLoaderRoute: typeof MerchantNavMerchantOrdersRouteImport
      parentRoute: typeof MerchantNavMerchantRoute
    }
    '/_merchantNav/merchant/profile': {
      id: '/_merchantNav/merchant/profile'
      path: '/profile'
      fullPath: '/merchant/profile'
      preLoaderRoute: typeof MerchantNavMerchantProfileRouteImport
      parentRoute: typeof MerchantNavMerchantRoute
    }
    '/_merchantNav/merchant/services': {
      id: '/_merchantNav/merchant/services'
      path: '/services'
      fullPath: '/merchant/services'
      preLoaderRoute: typeof MerchantNavMerchantServicesRouteImport
      parentRoute: typeof MerchantNavMerchantRoute
    }
    '/admin/applications/$id': {
      id: '/admin/applications/$id'
      path: '/admin/applications/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AdminApplicationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports/$id': {
      id: '/admin/reports/$id'
      path: '/admin/reports/$id'
      fullPath: '/admin/reports/$id'
      preLoaderRoute: typeof AdminReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/orders/$id': {
      id: '/merchant/orders/$id'
      path: '/merchant/orders/$id'
      fullPath: '/merchant/orders/$id'
      preLoaderRoute: typeof MerchantOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminNavAdminRouteChildren {
  AdminNavAdminProfileRoute: typeof AdminNavAdminProfileRoute
  AdminNavAdminReportsRoute: typeof AdminNavAdminReportsRoute
  AdminNavAdminReviewsRoute: typeof AdminNavAdminReviewsRoute
  AdminNavAdminIndexRoute: typeof AdminNavAdminIndexRoute
}

const AdminNavAdminRouteChildren: AdminNavAdminRouteChildren = {
  AdminNavAdminProfileRoute: AdminNavAdminProfileRoute,
  AdminNavAdminReportsRoute: AdminNavAdminReportsRoute,
  AdminNavAdminReviewsRoute: AdminNavAdminReviewsRoute,
  AdminNavAdminIndexRoute: AdminNavAdminIndexRoute,
}

const AdminNavAdminRouteWithChildren = AdminNavAdminRoute._addFileChildren(
  AdminNavAdminRouteChildren,
)

interface AdminNavRouteChildren {
  AdminNavAdminRoute: typeof AdminNavAdminRouteWithChildren
}

const AdminNavRouteChildren: AdminNavRouteChildren = {
  AdminNavAdminRoute: AdminNavAdminRouteWithChildren,
}

const AdminNavRouteWithChildren = AdminNavRoute._addFileChildren(
  AdminNavRouteChildren,
)

interface CustomerNavRouteChildren {
  CustomerNavExploreRoute: typeof CustomerNavExploreRoute
  CustomerNavOrdersRoute: typeof CustomerNavOrdersRoute
  CustomerNavProfileRoute: typeof CustomerNavProfileRoute
  CustomerNavIndexRoute: typeof CustomerNavIndexRoute
}

const CustomerNavRouteChildren: CustomerNavRouteChildren = {
  CustomerNavExploreRoute: CustomerNavExploreRoute,
  CustomerNavOrdersRoute: CustomerNavOrdersRoute,
  CustomerNavProfileRoute: CustomerNavProfileRoute,
  CustomerNavIndexRoute: CustomerNavIndexRoute,
}

const CustomerNavRouteWithChildren = CustomerNavRoute._addFileChildren(
  CustomerNavRouteChildren,
)

interface MerchantNavMerchantRouteChildren {
  MerchantNavMerchantOrdersRoute: typeof MerchantNavMerchantOrdersRoute
  MerchantNavMerchantProfileRoute: typeof MerchantNavMerchantProfileRoute
  MerchantNavMerchantServicesRoute: typeof MerchantNavMerchantServicesRoute
  MerchantNavMerchantIndexRoute: typeof MerchantNavMerchantIndexRoute
}

const MerchantNavMerchantRouteChildren: MerchantNavMerchantRouteChildren = {
  MerchantNavMerchantOrdersRoute: MerchantNavMerchantOrdersRoute,
  MerchantNavMerchantProfileRoute: MerchantNavMerchantProfileRoute,
  MerchantNavMerchantServicesRoute: MerchantNavMerchantServicesRoute,
  MerchantNavMerchantIndexRoute: MerchantNavMerchantIndexRoute,
}

const MerchantNavMerchantRouteWithChildren =
  MerchantNavMerchantRoute._addFileChildren(MerchantNavMerchantRouteChildren)

interface MerchantNavRouteChildren {
  MerchantNavMerchantRoute: typeof MerchantNavMerchantRouteWithChildren
}

const MerchantNavRouteChildren: MerchantNavRouteChildren = {
  MerchantNavMerchantRoute: MerchantNavMerchantRouteWithChildren,
}

const MerchantNavRouteWithChildren = MerchantNavRoute._addFileChildren(
  MerchantNavRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicOnboardingRoute: typeof PublicOnboardingRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicOnboardingRoute: PublicOnboardingRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminNavRoute: AdminNavRouteWithChildren,
  CustomerNavRoute: CustomerNavRouteWithChildren,
  MerchantNavRoute: MerchantNavRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  EditProfileRoute: EditProfileRoute,
  RegisterMerchantRoute: RegisterMerchantRoute,
  MerchantEditProfileRoute: MerchantEditProfileRoute,
  MerchantsIdRoute: MerchantsIdRoute,
  OrdersIdRoute: OrdersIdRoute,
  PaymentOrderIdRoute: PaymentOrderIdRoute,
  PaymentErrorRoute: PaymentErrorRoute,
  PaymentFinishRoute: PaymentFinishRoute,
  PaymentUnfinishRoute: PaymentUnfinishRoute,
  ReviewOrderIdRoute: ReviewOrderIdRoute,
  AdminApplicationsIdRoute: AdminApplicationsIdRoute,
  AdminReportsIdRoute: AdminReportsIdRoute,
  MerchantOrdersIdRoute: MerchantOrdersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
